services:

    Ofeige\ApiBundle\Service\HeaderInformation:
        autowire: true
        public: true

    Ofeige\ApiBundle\EventListener\HeaderResponseListener:
        autowire: true
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    Ofeige\ApiBundle\Describer\AnnotationDescriber:
        autowire: true
        public: false
        arguments:
            - '@nelmio_api_doc.routes.default'
            - '@nelmio_api_doc.controller_reflector'
        tags:
            - {name: 'nelmio_api_doc.route_describer', priority: -2000 }