services:

    Shopping\ApiHelperBundle\Service\HeaderInformation:
        autowire: true
        public: true

    Shopping\ApiHelperBundle\EventListener\HeaderResponseListener:
        autowire: true
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.response }